# Generated by Django 4.1.1 on 2024-07-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovacion', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliados',
            fields=[
                ('id_afiliado', models.AutoField(db_column='idAfiliado', primary_key=True, serialize=False)),
                ('nombre_afiliado', models.CharField(max_length=60)),
                ('rubro', models.CharField(max_length=50)),
            ],
        ),
    ]
