# Generated by Django 4.1.1 on 2024-07-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovacion', '0003_afiliados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Afiliados',
            new_name='Afiliado',
        ),
    ]
