# Generated by Django 4.1.1 on 2024-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovacion', '0004_rename_afiliados_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='monto_acelerado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
