# Generated by Django 4.1.1 on 2024-07-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovacion', '0005_afiliado_monto_acelerado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('nombre_Servicio', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
