# Generated by Django 4.1.1 on 2024-07-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovacion', '0006_servicios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
