# Generated by Django 4.1.1 on 2024-07-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovacion', '0007_rename_servicios_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='afiliado_urls',
            field=models.CharField(default='/home', max_length=60),
            preserve_default=False,
        ),
    ]
